#include "core/kfmtfile.h"

using namespace std::string_literals;

namespace KF1
{

constexpr KFMTFileListEntry fileList[] {
    // KF/B0
    {u"KF/B0/END", u"Epilogue", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B0/ENDG", u"Ending", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B0/L0", KFMTFile::FileType::MIX},
    {u"KF/B0/L0:0", u"Loading screen", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0", KFMTFile::FileType::MIX},
    {u"KF/B0/MIX0:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX0:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3", KFMTFile::FileType::MIX},
    {u"KF/B0/MIX3:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX3:8", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9", KFMTFile::FileType::MIX},
    {u"KF/B0/MIX9:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:8", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:9", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:10", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:11", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:12", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:13", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:14", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIX9:15", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B0/MIXB0", KFMTFile::FileType::MIX},
    {u"KF/B0/MIXB0:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B0/MIXB0:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B0/MIXB3", KFMTFile::FileType::MIX},
    {u"KF/B0/MIXB3:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B0/MIXBE", KFMTFile::FileType::MIX},
    {u"KF/B0/MIXBE:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B0/OPEN0", u"Intro Demo", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B0/OPEN1", u"Title Screen", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B0/OPEN3", u"Verdite Intro", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/B1
    {u"KF/B1/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/B1/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIX.TIM:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B1/MIXA.DAT", KFMTFile::FileType::MIX},
    {u"KF/B1/MIXA.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankHeader},
    {u"KF/B1/MIXA.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankBody},
    {u"KF/B1/MIXA.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXA.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXA.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXA.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXA.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXA.DAT:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXB.DAT", KFMTFile::FileType::MIX},
    {u"KF/B1/MIXB.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B1/MIXB.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B1/MIXB.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXB.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/MIXB.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B1/SND0.SEQ", u"Floor 1", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B1/SND1.SEQ", u"Floor 1-2", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B1/SND2.SEQ", u"Shop", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/B2
    {u"KF/B2/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/B2/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIX.TIM:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B2/MIXA.DAT", KFMTFile::FileType::MIX},
    {u"KF/B2/MIXA.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankHeader},
    {u"KF/B2/MIXA.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankBody},
    {u"KF/B2/MIXA.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXA.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXA.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXA.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXA.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXA.DAT:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXB.DAT", KFMTFile::FileType::MIX},
    {u"KF/B2/MIXB.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B2/MIXB.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B2/MIXB.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXB.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/MIXB.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B2/SND0.SEQ", u"Floor 2", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B2/SND1.SEQ", u"Floor 2-2", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/B3
    {u"KF/B3/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/B3/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIX.TIM:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B3/MIXA.DAT", KFMTFile::FileType::MIX},
    {u"KF/B3/MIXA.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankHeader},
    {u"KF/B3/MIXA.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankBody},
    {u"KF/B3/MIXA.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXA.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXA.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXA.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXA.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXA.DAT:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXB.DAT", KFMTFile::FileType::MIX},
    {u"KF/B3/MIXB.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B3/MIXB.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B3/MIXB.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXB.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/MIXB.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B3/SND0.SEQ", u"Floor 3", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/B4
    {u"KF/B4/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/B4/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIX.TIM:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B4/MIXA.DAT", KFMTFile::FileType::MIX},
    {u"KF/B4/MIXA.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankHeader},
    {u"KF/B4/MIXA.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankBody},
    {u"KF/B4/MIXA.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXA.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXA.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXA.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXA.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXA.DAT:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXB.DAT", KFMTFile::FileType::MIX},
    {u"KF/B4/MIXB.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B4/MIXB.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B4/MIXB.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXB.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/MIXB.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B4/SND0.SEQ", u"Floor 4", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/B5
    {u"KF/B5/CHR1.MIM", KFMTFile::FileType::MIX},
    {u"KF/B5/CHR1.MIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR1.MIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR1.MIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR1.MIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR1.MIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR1.MIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM", KFMTFile::FileType::MIX},
    {u"KF/B5/CHR2.MIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR2.MIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM", KFMTFile::FileType::MIX},
    {u"KF/B5/CHR3.MIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/CHR3.MIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/B5/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIX.TIM:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/B5/MIXA.DAT", KFMTFile::FileType::MIX},
    {u"KF/B5/MIXA.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankHeader},
    {u"KF/B5/MIXA.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::SoundBankBody},
    {u"KF/B5/MIXA.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXA.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXA.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXA.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXA.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXA.DAT:7", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXB.DAT", KFMTFile::FileType::MIX},
    {u"KF/B5/MIXB.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/MIXB.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Model},
    {u"KF/B5/MIXB.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXB.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/MIXB.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/B5/SND0.SEQ", u"Floor 5", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},
    {u"KF/B5/SND1.SEQ", u"Floor 5-2", KFMTFile::FileType::Raw, KFMTFile::DataType::MusicSequence},

    // KF/COM
    {u"KF/COM/COM.DAT", KFMTFile::FileType::MIX},
    {u"KF/COM/COM.DAT:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/COM.DAT:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::Unknown},
    {u"KF/COM/MIX.TIM", KFMTFile::FileType::MIX},
    {u"KF/COM/MIX.TIM:0", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:1", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:2", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:3", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:4", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:5", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/COM/MIX.TIM:6", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1", KFMTFile::FileType::Folder},
    {u"KF/ENE1/EI00.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI01.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI02.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI03.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI04.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI05.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI06.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI07.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI08.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE1/EI09.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2", KFMTFile::FileType::Folder},
    {u"KF/ENE2/EI00.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI01.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI02.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI03.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI04.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI05.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI06.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI07.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI08.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE2/EI09.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3", KFMTFile::FileType::Folder},
    {u"KF/ENE3/EI00.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI01.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI02.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI03.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI04.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI05.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE3/EI06.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4", KFMTFile::FileType::Folder},
    {u"KF/ENE4/EI00.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI01.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI02.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI03.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI04.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI05.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI06.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE4/EI07.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5", KFMTFile::FileType::Folder},
    {u"KF/ENE5/EI00.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI01.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI02.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI03.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI04.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI05.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI06.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI07.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
    {u"KF/ENE5/EI08.TIM", u"", KFMTFile::FileType::Raw, KFMTFile::DataType::TextureDB},
};

} // namespace KF1
