# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Build checksum_tool
      run: |
        cd Tools/checksum_tool
        qmake-qt5
        make -j4
        cd ..
    
    - name: Build fdat28_tool
      run: |
        cd Tools/fdat28_tool
        qmake-qt5
        make -j4
        cd ..
        
    - name: Build tfile_tool
      run: |
        cd Tools/tfile_tool
        qmake-qt5
        make -j4
        cd ..
