name: Build all projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-16.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.2 
      
    - name: Build checksum_tool
      run: |
        cd Tools/checksum_tool
        qmake
        make -j4
        cd ..
    
    - name: Build fdat28_tool
      run: |
        cd Tools/fdat28_tool
        qmake
        make -j4
        cd ..

    - name: Build KFRandomizer
      run: |
        cd Tools/KFRandomizer
        qmake
        make -j4
        cd ..
        
    - name: Build tfile_tool
      run: |
        cd Tools/tfile_tool
        qmake
        make -j4
        cd ..

    - name: Upload checksum_tool build
      uses: actions/upload-artifact@v2
      with:
        name: checksum_tool ubuntu build
        path: Tools/checksum_tool/checksum_tool
        
    - name: Upload fdat28_tool build
      uses: actions/upload-artifact@v2
      with:
        name: fdat28_tool ubuntu build
        path: Tools/fdat28_tool/fdat28_tool

    - name: Upload KFRandomizer build
      uses: actions/upload-artifact@v2
      with:
        name: KFRandomizer ubuntu build
        path: Tools/KFRandomizer/KFRandomizer
        
    - name: Upload tfile_tool build
      uses: actions/upload-artifact@v2
      with:
        name: tfile_tool ubuntu build
        path: Tools/tfile_tool/tfile_tool

  windows-build:
    runs-on: 	windows-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_mingw73
        version: 5.14.2 

    - name: Set static CFLAGS
      run: |
        setx CFLAGS -static -static-libstdc++
        setx CXXFLAGS -static -static-libstdc++
      
    - name: Build checksum_tool
      run: |
        echo %CFLAGS%
        echo %CXXFLAGS%
        cd Tools\checksum_tool
        qmake
        make -j4
        cd ..
    
    - name: Build fdat28_tool
      run: |
        cd Tools\fdat28_tool
        qmake
        make -j4
        cd ..

    - name: Build KFRandomizer
      run: |
        cd Tools\KFRandomizer
        qmake
        make -j4
        cd ..
        
    - name: Build tfile_tool
      run: |
        cd Tools\tfile_tool
        qmake
        make -j4
        cd ..

    - name: Deploy all tools
      run : |
        cd Tools\checksum_tool\release
        windeployqt --compiler-runtime checksum_tool.exe
        del *.o
        cd ..
        ren release checksum_tool
        cd ..\fdat28_tool\release
        windeployqt --compiler-runtime fdat28_tool.exe
        del *.o
        cd ..
        ren release fdat28_tool
        cd ..\KFRandomizer\release
        windeployqt --compiler-runtime KFRandomizer.exe
        del *.o
        cd ..
        ren release KFRandomizer
        cd ..\tfile_tool\release
        windeployqt --compiler-runtime tfile_tool.exe
        del *.o
        cd ..
        ren release tfile_tool
        cd ../..

    - name: Upload checksum_tool build
      uses: actions/upload-artifact@v2
      with:
        name: checksum_tool windows (64-bit) build
        path: Tools\checksum_tool\checksum_tool\
        
    - name: Upload fdat28_tool build
      uses: actions/upload-artifact@v2
      with:
        name: fdat28_tool windows (64-bit) build
        path: Tools\fdat28_tool\fdat28_tool\
        
    - name: Upload KFRandomizer build
      uses: actions/upload-artifact@v2
      with:
        name: KFRandomizer windows (64-bit) build
        path: Tools\KFRandomizer\KFRandomizer\
        
    - name: Upload tfile_tool build
      uses: actions/upload-artifact@v2
      with:
        name: tfile_tool windows (64-bit) build
        path: Tools\tfile_tool\tfile_tool\

