name: Build all projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.2 

    - name: Get linuxdeployqt
      run: | 
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage ~/.local/bin
        chmod +x ~/.local/bin/linuxdeployqt-continuous-x86_64.AppImage
      
    - name: Build checksum_tool
      run: |
        cd Tools/checksum_tool
        qmake
        make -j2
        cd ..
    
    - name: Build fdat28_tool
      run: |
        cd Tools/fdat28_tool
        qmake
        make -j2
        cd ..

    - name: Build KFModTool
      continue-on-error: true
      run: |
      
        cd Tools/KFModTool
        qmake
        make -j2
        cd ..

    - name: Build KFRandomizer
      run: |
        cd Tools/KFRandomizer
        qmake
        make -j2
        cd ..
        
    - name: Build tfile_tool
      run: |
        cd Tools/tfile_tool
        qmake
        make -j2
        cd ..

    - name: Deploy checksum_tool AppImage
      run: |
        cd Tools/checksum_tool
        linuxdeployqt-continuous-x86_64.AppImage -appimage checksum_tool

    - name: Upload checksum_tool build
      uses: actions/upload-artifact@v2
      with:
        name: checksum_tool ubuntu build
        path: Tools/checksum_tool/checksum_tool.AppImage
        
    - name: Upload fdat28_tool build
      uses: actions/upload-artifact@v2
      with:
        name: fdat28_tool ubuntu build
        path: Tools/fdat28_tool/fdat28_tool

    - name: Upload KFModTool build
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: KFModTool ubuntu build
        path: Tools/KFModTool/KFModTool

    - name: Upload KFRandomizer build
      uses: actions/upload-artifact@v2
      with:
        name: KFRandomizer ubuntu build
        path: Tools/KFRandomizer/KFRandomizer
        
    - name: Upload tfile_tool build
      uses: actions/upload-artifact@v2
      with:
        name: tfile_tool ubuntu build
        path: Tools/tfile_tool/tfile_tool

  windows-build:
    runs-on: 	windows-latest
    
    steps:
    - name: Set up Git for properly handling symlinks on Windows
      run: git config --global core.symlinks true

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_mingw73
        version: 5.14.2 

    - name: Build checksum_tool
      run: |
        cd Tools\checksum_tool
        qmake
        make -j2
        cd ..
    
    - name: Build fdat28_tool
      run: |
        cd Tools\fdat28_tool
        qmake
        make -j2
        cd ..

    - name: Build KFModTool
      continue-on-error: true
      run: |
        cd Tools\KFModTool
        qmake
        make -j2
        cd ..

    - name: Build KFRandomizer
      run: |
        cd Tools\KFRandomizer
        qmake
        make -j2
        cd ..
        
    - name: Build tfile_tool
      run: |
        cd Tools\tfile_tool
        qmake
        make -j2
        cd ..

    - name: Deploy checksum_tool
      run : |
        cd Tools\checksum_tool\release
        windeployqt --compiler-runtime checksum_tool.exe
        del *.o
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll .
        cd ..
        ren release checksum_tool

    - name: Deploy fdat28_tool
      run : |
        cd Tools\fdat28_tool\release
        windeployqt --compiler-runtime fdat28_tool.exe
        del *.o
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll .
        cd ..
        ren release fdat28_tool

    - name: Deploy KFModTool
      continue-on-error: true
      run : |
        cd Tools\KFModTool\release
        windeployqt --compiler-runtime KFModTool.exe
        del *.o
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll .
        cd ..
        ren release KFModTool

    - name: Deploy KFRandomizer
      run : |
        cd Tools\KFRandomizer\release
        windeployqt --compiler-runtime KFRandomizer.exe
        del *.o
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll .
        cd ..
        ren release KFRandomizer

    - name: Deploy tfile_tool
      run : |
        cd Tools\tfile_tool\release
        windeployqt --compiler-runtime tfile_tool.exe
        del *.o
        cp $env:Qt5_Dir\bin\libgcc_s_seh-1.dll .
        cp $env:Qt5_Dir\bin\libstdc++-6.dll .
        cp $env:Qt5_Dir\bin\libwinpthread-1.dll .
        cd ..
        ren release tfile_tool
        cd ../..

    - name: Upload checksum_tool build
      uses: actions/upload-artifact@v2
      with:
        name: checksum_tool windows (64-bit) build
        path: Tools\checksum_tool\checksum_tool\
        
    - name: Upload fdat28_tool build
      uses: actions/upload-artifact@v2
      with:
        name: fdat28_tool windows (64-bit) build
        path: Tools\fdat28_tool\fdat28_tool\
        
    - name: Upload KFModTool build
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: KFModTool windows (64-bit) build
        path: Tools\KFModTool\KFModTool\
        
    - name: Upload KFRandomizer build
      uses: actions/upload-artifact@v2
      with:
        name: KFRandomizer windows (64-bit) build
        path: Tools\KFRandomizer\KFRandomizer\
        
    - name: Upload tfile_tool build
      uses: actions/upload-artifact@v2
      with:
        name: tfile_tool windows (64-bit) build
        path: Tools\tfile_tool\tfile_tool\

